### ISSUE TITLE
Improve order confirmation and include as part of the standard checkout screens

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-theme-default#1]
Checkout should include the very last step that displays the confirmation for the order, including mini map of where it is shipped using google maps. Examples of the screens are below:

![order-conf1](https://user-images.githubusercontent.com/1566470/30300086-a8cefd9e-9707-11e7-9218-a16949c90dac.png)
![order-conf2](https://user-images.githubusercontent.com/1566470/30300087-a8d1a972-9707-11e7-9b9f-0aa60c00f99d.png)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-42
