### ISSUE TITLE
Fix error message in "Bulk order"

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-theme-default#103]
Please provide detailed information about your issue, thank you!

Version info: 
- Theme version: latest

### Expected behavior
Correct error messages displayed.

### Actual behavior
![image](https://user-images.githubusercontent.com/5801549/66460390-7b2fff00-ea7f-11e9-9724-d7a0723f1464.png)

### Steps to reproduce
1. go to "Bulk Order"
2. enter random strings in SKUs inputs
3. submit

**Comment by ilyawzrd** [comment]
https://github.com/VirtoCommerce/vc-theme-b2b/pull/166

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-theme-default/releases/edit/v2.0.5
Released: https://github.com/VirtoCommerce/vc-theme-b2b/releases/edit/v3.0.2
