### ISSUE TITLE
assets/static/bundle/ directory missing

### ISSUE THREAD

**Issue by sayron5** [VirtoCommerce/vc-theme-default#110]
The directory /static seems to be missing from the github repository and causes the following internal server error when attempting to load the template:

An unhandled exception occurred while processing the request.
StorefrontException: Theme resource for path 'static/bundle/scripts_dependencies.js' not found

VirtoCommerce.LiquidThemeEngine.ShopifyLiquidThemeEngine+<>c__DisplayClass37_0.<GetAssetHash>b__0(MemoryCacheEntryOptions cacheEntry) in ShopifyLiquidThemeEngine.cs, line 219

**Comment by yecli** [comment]
This info could be helpful, specifically packJavascript task running:
https://github.com/VirtoCommerce/vc-theme-default/#note
