### ISSUE TITLE
Facet search group prices: wrong place of decimal separator

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-theme-default#111]
@akak1977 commented on [Mon Sep 30 2019](https://github.com/VirtoCommerce/vc-storefront-core/issues/313)

Decimal separator in prices have wrong place:
![image](https://user-images.githubusercontent.com/9972421/65854012-c148dc80-e374-11e9-9106-d2fa7468abd3.png)

**Comment by akak1977** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.4
