### ISSUE TITLE
Remove duplicated breadcrumb item

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-theme-default#115]
Version info: 
- Theme version: latest

### Actual behavior
Last item is breadcrumbs is duplicated 

### Steps to reproduce
1. open any category/product

![image](https://user-images.githubusercontent.com/5801549/70061132-6b9ae580-15ec-11ea-8834-793796e43ea0.png)

**Comment by akak1977** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.4
