### ISSUE TITLE
Fix links in the footer

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-theme-default#116]
### Expected behavior
The links grom sample data should be opened correctly
### Actual behavior
Invalid links are generated the **Linked lists** in the footer
### Steps to reproduce
![image](https://user-images.githubusercontent.com/5801549/70061566-29be6f00-15ed-11ea-8e80-cfa3e14a401d.png)

**Comment by akak1977** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.4
