### ISSUE TITLE
"initialItems" is not defined in changeLineItemPrice method

### ISSUE THREAD

**Issue by artmakarov** [VirtoCommerce/vc-theme-default#134]
https://github.com/VirtoCommerce/vc-theme-default/blob/901ed6d6641ba46d5f4aa46aee4f2acd44953b68/assets/js/cart.js#L42

![2020-02-17_16-38-51](https://user-images.githubusercontent.com/37446577/74659361-3b9fbf00-51a5-11ea-84b3-cb7924394904.png)

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.1.3
