### ISSUE TITLE
Fix product details view

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-theme-default#137]
Version info: 
- Browser version:
- Storefront type:
  - [ ] for .NET Framework
  - [x ] for .NET Core
- Storefront version: latest
- Theme version: latest

### Expected behavior
buttons shown
### Actual behavior
theme depends on variation properties and script crashes, if no variation property found:
![image](https://user-images.githubusercontent.com/5801549/75445792-d00cdd00-596e-11ea-9823-dde23ae86747.png)

### Steps to reproduce
1. open product without variation property
2.

**Comment by yecli** [comment]
Release: https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.1.4
