### ISSUE TITLE
Variations tooglers is not shown on product page with platform v3

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-default#143]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome  80.0.3987.149
- Platform: last from release/3.0.0 on march 26, 2020. 4657cb472a77a07d0267c6f87c553a9b745c0071
- Storefront type:
  - [ ] for .NET Framework
  - [x] for .NET Core
- Storefront version:  last from dev on march 26, 2020
480b4b02b48acd17493ed34fc7c4ec4b535fa735
- Theme version: last from dev on march 26, 2020
818c023b3dea937acb9572a2fb265ae40b544d1a

### Expected behavior
Variatoins tooglers are shown.
![image](https://user-images.githubusercontent.com/13153256/77625791-46dccc00-6f55-11ea-9d96-036883e06255.png)

### Actual behavior
Tooglers are not shown. 
![image](https://user-images.githubusercontent.com/13153256/77626589-a12a5c80-6f56-11ea-8edb-9958ababb8bb.png)

### Steps to reproduce
1. Use the sample data on the environment that appropriate figured above version info. 
2. Go to the product with variations.

**Comment by akak1977** [comment]
Fixed in latest release\3.0.0
