### ISSUE TITLE
How to update the theme UI dynamically from vc platform ?

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-theme-default#176]
Hello, Is there any open-source utility or module available in this project which can help the user to dynamically change the look of the theme template from the admin panel(platform application) UI instead of changing via the source code of the theme?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6238 has been created

**Comment by yecli** [comment]
Such consulting questions better to ask on our community page:  https://www.virtocommerce.org/
We have page-builder module for constructing UI elements dynamically, maybe it could help: https://github.com/VirtoCommerce/vc-module-pagebuilder
