### ISSUE TITLE
Move all templates  strings in to the resources for allows to future localization 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-theme-default#19]
Hardcoded string examples:
https://github.com/VirtoCommerce/vc-theme-default/blob/master/snippets/recently-added-cart-item-dialog.liquid#L46

**Comment by n2pro** [comment]
Hardcoded strings moved to default file localization (en.default.json)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.2.0
