### ISSUE TITLE
Find all illegal encoding for theme files and  change to  Unicode (UTF with signature)

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-theme-default#25]

**Comment by artem-dudarev** [comment]
May be UTF-8?

**Comment by asvishnyakov** [comment]
Unicode (UTF-16, used in C# string), UTF-8, UTF-8 with BOM is different encodings. @tatarincev  Probably you mean UTF-8 with BOM? And there is no need to find and change encoding, just encode all files with something tool

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.0
