### ISSUE TITLE
Move account navigation to ui-router

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#26]
Currently we use ngComponentRouter for navigation inside customer account. It has some bugs, do not allow build breadcrumbs and (most important for me) do not allow to use $location.html5Mode(true). We use ui-router in our platform and, possible can use it here.

**Comment by Tilesto** [comment]
Same problem(

**Comment by tatarincev** [comment]
We don't have plans to involve many efforts to support and develop the current default-theme I think this issue can be closed. 
You may reopen this issue if it has been closed in error.
