### ISSUE TITLE
Refactor mainContext with promises

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#29]
Version info: 
- Browser version: Chrome 64
- Storefront type:
  - [ ] for .NET Framework
  - [x] for .NET Core
- Storefront version: 3.0.10
- Theme version: 1.3.0

### Expected behavior
When need to wait while customer loaded, use promises and .then method

### Actual behavior
Because mainContext doesn't return promise, we need to use angular's watch

**Comment by tatarincev** [comment]
We haven't further planned to involve a lot of effort in order to support and develop the current default theme. I think this problem can be closed.
You can open this problem if it was closed by mistake.
