### ISSUE TITLE
Reset password does not work

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#31]
@n2pro commented on [Fri Mar 02 2018](https://github.com/VirtoCommerce/vc-platform/issues/1295)

I'm using a standard theme, when I try to recover a password, I redirect to the error page 
**Not enough info for reseting password**

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.1
