### ISSUE TITLE
Major markup issues in layout files

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-theme-default#37]
I made a fork where I want to use Foundation grid but while trying to do so I stumbled upon some major markup issues with liquid files.

Just to point out a few:

In `theme.liquid` you have the following markup snippet

```
 <div class="grid--full">
                <div class="grid-item large--one-third">
                    {% if template == 'index' %}
                    <h1 class="header-logo" itemscope itemtype="http://schema.org/Organization">
                        {% else %}
                        <div class="h1 header-logo" itemscope itemtype="http://schema.org/Organization">
                            {% endif %}
                            {% if settings.logo_use_image %}
                            <a href="{{ '/' | absolute_url }}" itemprop="url">
                                <img alt="{{ shop.name }}" src="{{ 'logo.png' | asset_url }}" itemprop="logo" />
                            </a>
                            {% else %}
                            <a href="{{ '/' | absolute_url }}" itemprop="url">{{ shop.name }}</a>
                            {% endif %}
                            {% if template == 'index' %}
                    </h1>
                    {% else %}
                </div>
                {% endif %}
            </div>
```
There is this line 

`<div class="h1 header-logo" itemscope itemtype="http://schema.org/Organization">`

which doesn't have a closing `</div>`. There is also an issue of `{% endif %}` being incorrectly nested given how the opening `if` is nested.

Then in `account_layout.liquid` there is this line

`<div class="h1 header-logo" itemscope itemtype="http://schema.org/Organization" />`

which is incorrect again as `<div>` cannot be self-closed.

I wonder how many more markup issues like the ones I discovered are there within the liquid files.

**Comment by yecli** [comment]
Released in [v1.3.3](https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.3).
