### ISSUE TITLE
Move image assets into assets/images folder

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-theme-default#38]
Currently all the image assets are under the assets folder which makes working with other (non image) files within the assets folder hard because the file tree expands all the way down in all major IDEs because of the long list of image files. These should be moved into /assets/images and paths should be corrected.

**Comment by yecli** [comment]
Released in [v1.3.3](https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.3).
