### ISSUE TITLE
Eliminate the all js dependencies that are loaded from CDN resources. Use local version instead.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-theme-default#46]
Need to move all js packages that are loaded from CDN resources in these files:
https://github.com/VirtoCommerce/vc-theme-default/blob/master/layout/theme.liquid
https://github.com/VirtoCommerce/vc-theme-default/blob/master/layout/checkout_layout.liquid
https://github.com/VirtoCommerce/vc-theme-default/blob/master/layout/account_layout.liquid

into  `bundle/scripts.js` bundle which is included in the layout page by this statement
` {{ 'bundle/scripts.js' | static_asset_url | append_version | script_tag }}`

Technical details:
I guess we can use for this `bower` package manager. See how it done in the platform https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/gulpfile.js#L18

**Comment by yecli** [comment]
Released in [v1.3.3](https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.3).
