### ISSUE TITLE
Fix the behavior of adding a product to a shopping/wish list

### ISSUE THREAD

**Issue by Andrew-Orlov** [VirtoCommerce/vc-theme-default#54]
Shopping/wish list should be transient until saving with some products. A collection of lists should be stored in store theme settings. Be sure that personal cabinet should not create a persistent lists.

**Comment by Andrew-Orlov** [comment]
https://github.com/VirtoCommerce/vc-theme-default/pull/56

**Comment by Andrew-Orlov** [comment]
There is another issue. To reproduce it just create a new customer on storefront, after that go to product page and click "Add to list" button. Storefront API will return 400.

![capture.gif](https://images.zenhubusercontent.com/56b873cb6caf56c9d38c4e91/0e233fee-e192-48f1-bfcf-f6c3cfc88167)

**Comment by yecli** [comment]
Released in [v1.3.3](https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v1.3.3).
