### ISSUE TITLE
Some dictionary properties on a product details page contains 'undef' selectable value

### ISSUE THREAD

**Issue by Andrew-Orlov** [VirtoCommerce/vc-theme-default#58]
**Describe the bug**
Some dictionary properties on a product details page contains 'undef' selectable value.

**Steps to reproduce**
1. Go to '.../Electronics/en-US/cell-phones/11'
2. See 'Color' property

**Expected behavior**
Option 'undef' shouldn't be presented at the storefront at all.

**Screenshots (optional)**
![image.png](https://images.zenhubusercontent.com/56b873cb6caf56c9d38c4e91/a1eafbb9-e648-43cf-9a5a-8b13c037b166)

**Version info (please complete the following information):**
 - Browser version: All browsers
 - Platform version: All versions

**Comment by tatarincev** [comment]
Need to fix sample data

**Comment by yecli** [comment]
Please check all the products on [demo](https://demo.virtocommerce.com/) site if they contains 'undef' value like in filter.
Need to get following table:
property name with undef - page URL.
Then these properties will be fixed in database.

**Comment by ilyawzrd** [comment]
@yecli,only cell phones have this
[Undef.docx](https://github.com/VirtoCommerce/vc-theme-default/files/2941806/Undef.docx)

**Comment by yecli** [comment]
Good, will handle these errors in data.

**Comment by yecli** [comment]
Here is the catalog binary file with fixed data: 
https://drive.google.com/open?id=1Xz7HcG7_b-gsnOgi4uCDEWSyLS8awZFd
@tatarincev Could you try it?
