### ISSUE TITLE
Breadcrumbs missed for nested collections

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#6]
How to reproduce:
1. Go to any nested collection in sample data (for example, `Televisions → Lg`)
2. Look at breadcrumbs. It should be `Home → Televisions → Lg`, but `Home → Lg` appear instead.

Looks like this code https://github.com/VirtoCommerce/vc-theme-default/blob/master/snippets/breadcrumb.liquid#L9 should also appear here https://github.com/VirtoCommerce/vc-theme-default/blob/master/snippets/breadcrumb.liquid#L52

**Comment by OlegoO** [comment]
OK on product page:
http://demo.virtocommerce.com/Electronics/en-US/televisions/lg/lg-eg9600-series-55-class-4k-smart-curved-ole

Problem with category page:
http://demo.virtocommerce.com/Electronics/en-US/televisions/lg

**Comment by vkrashenko** [comment]
![breadcrumbs](https://user-images.githubusercontent.com/29459286/30438864-97485b5c-9972-11e7-8ee2-0b5c37950476.gif)

**Comment by asvishnyakov** [comment]
Fixed.
