### ISSUE TITLE
Google sign in doesn't work on demo site Electonics theme

### ISSUE THREAD

**Issue by 5309** [VirtoCommerce/vc-theme-default#64]
### Steps to reproduce
1. Go to https://demo.virtocommerce.com/Electronics/en-US/account/login
2. Click "Google" button

![image](https://user-images.githubusercontent.com/30014191/50476582-37da3780-09fb-11e9-897b-0a3a0ff3469c.png)

### Expected behavior

Google sign in page

### Actual behavior

![image](https://user-images.githubusercontent.com/30014191/50476682-930c2a00-09fb-11e9-9154-e403da330ec9.png)

**Comment by tatarincev** [comment]
Done by set the new auth keys
