### ISSUE TITLE
Support Two factor authentication in Login form

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-theme-default#70]
### Login form
**User stories:**

- As **User** I want to login in the store only after confirming the code received  via SMS if Two factor authentication is enabled in my cabinet.  

Technical details:
Need to add liquid template templates\customers\verify-code.liquid into default theme. 
It should in storefront theme style like this in storefront theme style:
![image](https://user-images.githubusercontent.com/15610352/51996575-d82deb00-24d6-11e9-9096-66ecfe362b72.png)

Code input should be named "customer[verification_code]", checkbox - "customer[remember_browser]".

**Comment by yecli** [comment]
@ilyawzrd Please check templates\verify-code.liquid template from the latest commit. It contains proper mappings, need to add labels, translations, position elements properly.

**Comment by ilyawzrd** [comment]
@yecli Updated version
(Form
https://github.com/VirtoCommerce/vc-theme-default/pull/71/commits/f6b8bd3afbab399bc990db4ee71349bfc591508a
![enter verification code](https://user-images.githubusercontent.com/22875828/52634045-d1d44180-2ece-11e9-86da-5fc00d86e632.png)

**Comment by ilyawzrd** [comment]
@yecli,I also checked behaviour of checkbox button - it works fine
66e54bc89659f215d7bfc3eefcc564841558ceb2
![43](https://user-images.githubusercontent.com/22875828/52737189-6379a700-2fd4-11e9-89b4-fbe5f4a2af87.png)

**Comment by yecli** [comment]
Good, seems ok. Will check in complex when other subtasks will be ready.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.0
