### ISSUE TITLE
possible exception with minification

### ISSUE THREAD

**Issue by kamilgarey** [VirtoCommerce/vc-theme-default#76]
js minification now take scripts in alphabetical order. Usually files need only reference to angular module storefrontApp (over dependencies comes thru angular DI)  . As it is declared in app.js which usually comes first in minification order  we have no problems. But if we create a file who comes first in order and reference to module (which we usually do) we'll got angular error in storefront after minification .

### Steps to reproduce
1. add "answer.js" to assets/js which contains 
"
angular.module('storefrontApp');
"
2. minify
3.Update browser cache.

**Comment by yecli** [comment]
Moved to "On hold" as theme bundling is going to be reworked.

**Comment by eMazeika** [comment]
that's a "well known old issue". Hopefully, we can get new recommendations / solution on this after "reworked".

**Comment by tatarincev** [comment]
This issue has been closed because it has no longer relevant to the current operation nature of issues.
You may reopen this issue if it has been closed in error.
