### ISSUE TITLE
Review, reformat, refactor and cleanup theme

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#8]
1. Theme contains old and obsolete code. For example:
(dead and never used)
https://github.com/VirtoCommerce/vc-theme-default/blob/master/snippets/slider.liquid
(liquid → angular)
https://github.com/VirtoCommerce/vc-theme-default/blob/master/layout/theme.liquid#L92
2. Sometimes code is wrong formatted, so it's not simple to understand what it doing:
https://github.com/VirtoCommerce/vc-theme-default/blob/master/layout/theme.liquid#L89

Review, reformat and cleanup theme to make it more readable.

Also, we possible may change structure of code: separate some files to small parts (one task - one file; like one class - one file in C#) and move some files to subfolder to simplify & file list in single folder.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
