### ISSUE TITLE
Bower is giving 502 error in fresh install of Visual Studio 2017 

### ISSUE THREAD

**Issue by HtrBr** [VirtoCommerce/vc-theme-default#80]
Add .bowererrc file to project with following content 

{
    "registry": "https://registry.bower.io"
}

_Originally posted by @HtrBr in https://github.com/VirtoCommerce/vc-theme-default/pull/61#issuecomment-484443850_

**Comment by AliveMen** [comment]
You should update bower to any version upper 1.8.2
https://github.com/bower/bower/releases/tag/v1.8.2
