### ISSUE TITLE
Can't show "Sign in/Create an account" links.

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-default#83]
Solve this problem. 

For more details see description of problem into parrent <a href="https://github.com/VirtoCommerce/vc-theme-default/issues/79#issuecomment-484914019">Epic issues comment</a> from <b>ilyawzrd</b>.

- https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/layout/account_layout.liquid#L80
- https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/layout/theme.liquid#L90

**Comment by trueboroda** [comment]
Problem in that the data context (WorkContext) don't have property need to perform condition properly.
Workt context don't have shop.customer_accounts_enabled property. I guess this is a rudiment.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.0
