### ISSUE TITLE
It shows an error that something wrong with "For" loop.

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-default#84]
Solve this problem.

For more details see description of problem into parrent <a href="https://github.com/VirtoCommerce/vc-theme-default/issues/79#issuecomment-484914019">Epic issues comment</a> from <b>ilyawzrd</b>.

https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/templates/list-collections.liquid#L6

**Comment by ilyawzrd** [comment]
https://github.com/VirtoCommerce/vc-theme-default/commit/71e4468a67ac29f8c9c239ff4ebca5ba9c964886
We don't have 'all-collections' list, is this a rudiment?
