### ISSUE TITLE
"For" loop is not working in snippets/collection-sidebar.liquid

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-default#86]
Solve this problem.

https://github.com/VirtoCommerce/vc-theme-default/blob/1e1c422f3e378e38140cdf64a8ae351636218072/snippets/collection-sidebar.liquid#L4

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.0
