### ISSUE TITLE
Site search error must be eliminated

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-default#88]
When you a searching by any text on site error occurs.
![image.png](https://images.zenhubusercontent.com/5cc6e4f02f5ec15dfd0d40cf/8cdd2754-c9f3-4dff-a37e-df9a2c3cdf73)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.0
