### ISSUE TITLE
Newsletter subscription does not work

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-default#9]
404 error occurs when you try to subscribe

**Comment by megafreeman** [comment]
Need to add form action through the config file and AntiForgeryToken support

**Comment by Woland2k** [comment]
No, the form is tied automatically through autopilot, not using our standard logic.

**Comment by vkrashenko** [comment]
we doesnt have any services on storefront which work with subscription, first need to create it

**Comment by tatarincev** [comment]
We do not have plans to implement subscriptions service on our side. This functionality should be achieved through integrations with 3rd party services.
