### ISSUE TITLE
Copyright doesn't display correctly in the footer

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-theme-default#92]
### Expected behavior
Should display normal copyright

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/63489075-f4d74380-c465-11e9-8c04-9ed9a507a246.png)

**Comment by eMazeika** [comment]
was it released?

**Comment by yecli** [comment]
It is still here.
@blazemachine Could you check this bug?

**Comment by tatarincev** [comment]
@Fixed
