### ISSUE TITLE
Fix errors messages in "Change password" tab

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-theme-default#93]
Version info: 
- Storefront type:
  - [ ] for .NET Framework
  - [ x] for .NET Core
- Storefront version: 
- Theme version: latest on demo

### Expected behavior
Correct error messages displayed
### Actual behavior
"[object Object]" displayed
### Steps to reproduce
1. sign in
2. open "Change password" under "My account"
3. a) enter incorrect current password and submit
3. b) enter correct current password and "a" as a new password and submit

**Comment by blazemachine** [comment]
![scenario a](https://user-images.githubusercontent.com/43133766/64961836-c192a380-d8af-11e9-9110-8bfb891048f4.gif)
![scenario b](https://user-images.githubusercontent.com/43133766/64961837-c22b3a00-d8af-11e9-976b-9058d40c17d3.gif)

**Comment by eMazeika** [comment]
![image](https://user-images.githubusercontent.com/5801549/64963896-a8372a80-d8a2-11e9-91e3-83b2922baad4.png)

**Comment by blazemachine** [comment]
It has not published on demo yet.

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.2
